# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  override_default_tags = {}
  default_tags = {
    Squad = "devops"
    Terragrunt = "true"
    Environment = "POC"
    Path = "vpc-endpoint"
  }

  override_ignore_tags_key_prefixes = []
  ignore_tags_key_prefixes = []
    
  override_ignore_tags_keys = []
  ignore_tags_keys = []
}

provider "aws" {
  default_tags { tags = merge(local.default_tags, local.override_default_tags) }
  region = "us-west-2"

  ignore_tags {
    keys = concat(local.ignore_tags_keys, local.override_ignore_tags_keys)
    key_prefixes = concat(local.ignore_tags_key_prefixes, local.override_ignore_tags_key_prefixes)
  }
}
